"""name and surname added

Revision ID: 15234b0cc41d
Revises: d9e670a1aff7
Create Date: 2023-08-19 16:40:48.134495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15234b0cc41d'
down_revision = 'd9e670a1aff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('surnaname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('surnaname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
