"""accuracyValue column added

Revision ID: 3231eccb322c
Revises: 600f267106fc
Create Date: 2023-09-05 15:49:12.698525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3231eccb322c'
down_revision = '600f267106fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracyValue', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.drop_column('accuracyValue')

    # ### end Alembic commands ###
