"""csv-data column added

Revision ID: 37c84e9018e0
Revises: 5de68bde6f6f
Create Date: 2023-09-04 20:26:19.235891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c84e9018e0'
down_revision = '5de68bde6f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csvData', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.drop_column('csvData')

    # ### end Alembic commands ###
