"""droppedcolumns added

Revision ID: 5d5bdaa1618d
Revises: 54ea31531faf
Create Date: 2023-09-06 09:42:11.286128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5bdaa1618d'
down_revision = '54ea31531faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listOfLabels', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('droppedColumns', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.drop_column('droppedColumns')
        batch_op.drop_column('listOfLabels')

    # ### end Alembic commands ###
