"""model speacial name added

Revision ID: 600f267106fc
Revises: 37c84e9018e0
Create Date: 2023-09-05 13:16:01.087914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600f267106fc'
down_revision = '37c84e9018e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelSpecialName', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savedmodels', schema=None) as batch_op:
        batch_op.drop_column('modelSpecialName')

    # ### end Alembic commands ###
